### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by wzxuhuaiyuan** [Lu-Feng/STA-VPR#1]
Hi, Lu Feng! Could you tell me where I can download the datasets for this code?  Like Nordland,  Gardens Point, UA, and Berlin A100.

Thanks.

**Comment by Lu-Feng** [comment]
> Hi, Lu Feng! Could you tell me where I can download the datasets for this code? Like Nordland, Gardens Point, UA, and Berlin A100.
> 
> Thanks.

Thanks for your interest in our work. We have added download link for each dataset on the homepage. Hope to be helpful to you.
