### ISSUE TITLE
Questions about code results

### ISSUE THREAD

**Issue by jialeB** [Lu-Feng/STA-VPR#2]
Hi, Lu Feng! I'm very interested in your work. But when I run the 'STAVPRdemo.py', it's not like the good performance showed in your paper. Could you tell why, and how can modify code parameters?

**Comment by Lu-Feng** [comment]
> Hi, Lu Feng! I'm very interested in your work. But when I run the 'STAVPRdemo.py', it's not like the good performance showed in your paper. Could you tell why, and how can modify code parameters?

Thanks for your interest in our work. Can you tell me which dataset you test on? For Gardens Point dataset (day_left vs. night_right) you can run the STAVPRdemo.py directly. For other datasets you need to modify the input parameters in STAVPRconfig.yaml.

**Comment by jialeB** [comment]
![image](https://user-images.githubusercontent.com/88070755/146767731-c3a42b61-5944-4aa3-8cb3-a2ace5db28a6.png)

I have run the code on both dataset. I got the P-R result on Nordland3584  and showed it below.   I only changed the paths to the datasets and the  format of Images according to the readme. md file.

**Comment by Lu-Feng** [comment]
> ![image](https://user-images.githubusercontent.com/88070755/146767731-c3a42b61-5944-4aa3-8cb3-a2ace5db28a6.png)
> 
> I have run the code on both dataset. I got the P-R result on Nordland3584 and showed it below. I only changed the paths to the datasets and the format of Images according to the readme. md file.

Did you get the same result on the Gardens Point dataset? Can you send me your STAVPRconfig.yaml file and output details (like "current query sequence: xxxx   midpoint: xxxx  result: xxxx  midpoint: xxxx  min seq distance: 0.xxx")

**Comment by jialeB** [comment]
On the Gardens dataset, the results are shown below.
![image](https://user-images.githubusercontent.com/88070755/146853516-8d3ae728-7a95-4df1-ae0b-5055d0c93423.png)
![image](https://user-images.githubusercontent.com/88070755/146853576-d4ad83f2-9c62-49ad-92fd-f8f39fe37f40.png)
![image](https://user-images.githubusercontent.com/88070755/146853644-e036752a-92e4-4117-935e-8ff8f4202f07.png)
![image](https://user-images.githubusercontent.com/88070755/146853726-be8119cf-363c-4953-86fa-cb10a2b7a430.png)

**Comment by Lu-Feng** [comment]
I guess there is something wrong when extracting features by VGG. Please check the versions of TensorFlow and Keras, or try again with the densenet (use PyTorch) instead.

**Comment by jialeB** [comment]
> 
Thank you for answering my questions patiently. After I changed the versions of TensorFlow and Keras,  I still got the wrong result. When I try to extract feature using densenet, the program reported an error. Could you tell me how to modify it? Thanks so much again.
![image](https://user-images.githubusercontent.com/88070755/146903540-0cc4d30e-d047-46eb-9ad7-e106f4adb9a9.png)

**Comment by Lu-Feng** [comment]
Are the pyTorch version and pre-trained DenseNet model the same as README.md? Can you send me a copy of your code via email

**Comment by jialeB** [comment]
> 
 I have sent my code to your email "lufengrv@gmail.com". Looking forward to your reply.
